title: Stackbit Vanilla Theme
baseURL: /
params:
  header:
    content: Stackbit Vanilla
    has_nav: true
  footer:
    content: '&copy; Stackbit-Vanilla. All rights reserved.'
    links:
      - text: Made with Stackbit
        url: 'https://www.stackbit.com'
        new_window: true
disableKinds:
  - RSS
